---

- hosts: all
  become: true
  tasks:

  - name: install apache2 package
    apt:
      name: apache2
      state: latest

  - name: add php supp for apache
    apt:
      name: libapache2-mod-php
      state: latest
